configs:
  authelia:
    file: ./authelia.yaml
    name: authelia-${HASH_AUTHELIA}
  authelia-users:
    file: ./authelia-users.yaml
    name: authelia-users-${HASH_AUTHELIA_USERS}
  grafana:
    file: ./grafana.ini
    name: grafana-${HASH_GRAFANA}
  logo:
    file: ./logo.png
    name: logo-${HASH_LOGO}
  loki:
    file: ./loki.yaml
    name: loki-${HASH_LOKI}
  ntfy:
    file: ./ntfy.yaml
    name: ntfy-${HASH_NTFY}
  prometheus:
    file: ./prometheus.yaml
    name: prometheus-${HASH_PROMETHEUS}
  promtail:
    file: ./promtail.yaml
    name: promtail-${HASH_PROMTAIL}
networks:
  outsideworx:
    external: true
secrets:
  rsa_private_key:
    external: true
services:
  authelia:
    configs:
      - source: authelia
        target: /config/configuration.yml
      - source: authelia-users
        target: /config/users.yaml
      - source: logo
        target: /config/assets/logo.png
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.authelia.entrypoints=websecure
        - traefik.http.routers.authelia.rule=Host(`oauth.outsideworx.net`)
        - traefik.http.routers.authelia.tls.certresolver=letsencrypt
        - traefik.http.services.authelia.loadbalancer.server.port=80
    environment:
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: $AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /run/secrets/rsa_private_key
      AUTHELIA_JWT_SECRET: $AUTHELIA_JWT_SECRET
      AUTHELIA_SESSION_SECRET: $AUTHELIA_SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY: $AUTHELIA_STORAGE_ENCRYPTION_KEY
    healthcheck:
      disable: true
    image: authelia/authelia:4.37
    networks:
      outsideworx:
        aliases:
          - services-authelia
    secrets:
      - rsa_private_key
  grafana:
    configs:
      - source: grafana
        target: /etc/grafana/grafana.ini
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.rule=Host(`grafana.outsideworx.net`)
        - traefik.http.routers.grafana.tls.certresolver=letsencrypt
        - traefik.http.services.grafana.loadbalancer.server.port=80
    environment:
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: $GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
    image: grafana/grafana:12.3.0
    networks:
      - outsideworx
    user: root
    volumes:
      - grafana:/var/lib/grafana
  loki:
    configs:
      - source: loki
        target: /etc/loki/local-config.yaml
    deploy:
      placement:
        constraints:
          - node.role == manager
    image: grafana/loki:3.6.4
    networks:
      - outsideworx
    user: root
    volumes:
      - loki:/loki
  ntfy:
    command: serve
    configs:
      - source: ntfy
        target: /etc/ntfy/server.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.ntfy.entrypoints=websecure
        - traefik.http.routers.ntfy.rule=Host(`ntfy.outsideworx.net`)
        - traefik.http.routers.ntfy.tls.certresolver=letsencrypt
        - traefik.http.services.ntfy.loadbalancer.server.port=80
    environment:
      NTFY_WEB_PUSH_PRIVATE_KEY: $NTFY_WEB_PUSH_PRIVATE_KEY
      NTFY_WEB_PUSH_PUBLIC_KEY: $NTFY_WEB_PUSH_PUBLIC_KEY
    image: binwiederhier/ntfy:v2.16.0
    networks:
      - outsideworx
    volumes:
      - ntfy:/etc/ntfy/data
  postgres:
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
    image: postgres:16.2
    networks:
      outsideworx:
        aliases:
          - services-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  postgres-exporter:
    command:
      - --web.listen-address=:80
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      DATA_SOURCE_PASS: $SPRING_DATASOURCE_PASSWORD
      DATA_SOURCE_URI: services_postgres:5432/?sslmode=disable
      DATA_SOURCE_USER: $SPRING_DATASOURCE_USERNAME
    image: quay.io/prometheuscommunity/postgres-exporter:v0.18.1
    networks:
      - outsideworx
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=365d
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
    image: prom/prometheus:v3.9.1
    networks:
      - outsideworx
    user: root
    volumes:
      - prometheus:/prometheus
  promtail:
    configs:
      - source: promtail
        target: /etc/promtail/config.yml
    deploy:
      mode: global
    image: grafana/promtail:3.6.4
    networks:
      - outsideworx
    volumes:
      - promtail:/promtail
      - /var/run/docker.sock:/var/run/docker.sock:ro
  services:
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.services.entrypoints=websecure
        - traefik.http.routers.services.rule=Host(`services.outsideworx.net`)
        - traefik.http.routers.services.tls.certresolver=letsencrypt
        - traefik.http.services.services.loadbalancer.server.port=80
    environment:
      APP_CLIENTS_CIAFO_TOKEN: $APP_CLIENTS_CIAFO_TOKEN
      APP_CLIENTS_PEEPS_TOKEN: $APP_CLIENTS_PEEPS_TOKEN
      APP_CLIENTS_SOUP_TOKEN: $APP_CLIENTS_SOUP_TOKEN
      MAILERSEND_SDK_TOKEN: $MAILERSEND_SDK_TOKEN
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTHELIA_CLIENT_SECRET: $SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTHELIA_CLIENT_SECRET
    image: ghcr.io/outsideworx/services:latest
    networks:
      outsideworx:
        aliases:
          - services-services
  traefik:
    command:
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=info@outsideworx.net
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.traefik.address=:81
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --log.noColor=true
      - --metrics.prometheus=true
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
    deploy:
      placement:
        constraints:
          - node.role == manager
    image: traefik:v3.6.14
    networks:
      - outsideworx
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  utils:
    command: >-
      bash -c '
        cd /etc/utils;
        pip install -r requirements.txt -q &&
        for script in *.py; do
          [[ "$$script" == *.draft.py ]] && continue;
          python "$$script" &
        done;
        wait'
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      DB_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      DB_USERNAME: $SPRING_DATASOURCE_USERNAME
      NTFY_DB_PATH: /etc/ntfy/data/user.db
    image: python:3.13-slim
    networks:
      - outsideworx
    volumes:
      - ntfy:/etc/ntfy/data
      - /home/outsideworx/utils:/utils
      - ./utils:/etc/utils
volumes:
  grafana:
  letsencrypt:
  loki:
  ntfy:
  postgres:
  prometheus:
  promtail: