services:
  authelia:
    container_name: authelia
    image: authelia/authelia:4.37
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`oauth.localhost`)
      - traefik.http.routers.authelia.tls=true
      - traefik.http.services.authelia.loadbalancer.server.port=80
    volumes:
      - ./authelia-test.yaml:/config/configuration.yml
      - ./authelia-test-users.yaml:/config/users.yaml
      - ./logo.png:/config/assets/logo.png
  grafana:
    container_name: grafana
    image: grafana/grafana:12.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=80
    volumes:
      - ./grafana-test.ini:/etc/grafana/grafana.ini
  loki:
    container_name: loki
    image: grafana/loki:3.6.4
    ports:
      - "3100:3100"
  ntfy:
    command: serve
    container_name: ntfy
    image: binwiederhier/ntfy:v2.16.0
    volumes:
      - ntfy:/etc/ntfy/data
      - ./ntfy-test.yaml:/etc/ntfy/server.yml
  postgres:
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:16.2
    ports:
      - "5432:5432"
  postgres-exporter:
    command:
      - --web.listen-address=:81
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_PASS:
      DATA_SOURCE_URI: postgres:5432/?sslmode=disable
      DATA_SOURCE_USER: postgres
    image: quay.io/prometheuscommunity/postgres-exporter:v0.18.1
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.9.1
    volumes:
      - ./prometheus-test.yaml:/etc/prometheus/prometheus.yml
  traefik:
    container_name: traefik
    image: traefik:v3.6.12
    command:
      - --accesslog=true
      - --entrypoints.traefik.address=:81
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --metrics.prometheus=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/.docker/run/docker.sock:/var/run/docker.sock:ro
  utils:
    command: >-
      bash -c '
        cd /etc/utils;
        pip install -r requirements.txt -q &&
        for script in *.py; do
          python "$$script" &
        done;
        wait'
    container_name: utils
    environment:
      DB_PASSWORD: ""
      DB_USERNAME: postgres
      LOKI_PORT: 3100
      NTFY_DB_PATH: /etc/ntfy/data/user.db
    image: python:3.13-slim
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia/api/verify?rd=https://oauth.localhost
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.middlewares=authelia
      - traefik.http.routers.ntfy.rule=Host(`ntfy.localhost`)
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.services.ntfy.loadbalancer.server.port=80
    volumes:
      - ntfy:/etc/ntfy/data
      - ./utils:/etc/utils
volumes:
  ntfy: