services:
  grafana:
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    image: grafana/grafana:12.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.services.grafana.loadbalancer.server.port=81
    volumes:
      - ./grafana-test.ini:/etc/grafana/grafana.ini
  loki:
    container_name: loki
    image: grafana/loki:3.6.4
    ports:
      - "3100:3100"
  ntfy:
    command: serve
    container_name: ntfy
    image: binwiederhier/ntfy:v2.16.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.rule=Host(`ntfy.localhost`)
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    volumes:
      - ./ntfy-test.yaml:/etc/ntfy/server.yml
  postgres:
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:16.2
    ports:
      - "5432:5432"
  postgres-exporter:
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: postgres:5432/?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.18.1
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.9.1
    volumes:
      - ./prometheus-test.yaml:/etc/prometheus/prometheus.yml
  traefik:
    container_name: traefik
    image: traefik:v3.6.12
    command:
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --metrics.prometheus=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
    volumes:
      - $HOME/.docker/run/docker.sock:/var/run/docker.sock:ro
  utils:
    command: >-
      bash -c '
      cd /etc/utils &&
      pip install -r requirements.txt -q &&
      for script in *.py;
      do python "$$script" & done;
      wait'
    container_name: utils
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD:
      LOKI_PORT: 3100
    image: python:3.13-slim
    volumes:
      - ./utils:/etc/utils