services:
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
    image: grafana/grafana:12.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.rule=Host(`grafana.outsideworx.net`)
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=80
    restart: unless-stopped
    user: root
    volumes:
      - /home/outsideworx/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
  loki:
    container_name: loki
    image: grafana/loki:3.6.4
    restart: unless-stopped
    user: root
    volumes:
      - /home/outsideworx/loki:/loki
      - ./loki.yaml:/etc/loki/local-config.yaml
  ntfy:
    command: serve
    container_name: ntfy
    environment:
      NTFY_WEB_PUSH_PUBLIC_KEY: $NTFY_WEB_PUSH_PUBLIC_KEY
      NTFY_WEB_PUSH_PRIVATE_KEY: $NTFY_WEB_PUSH_PRIVATE_KEY
    image: binwiederhier/ntfy:v2.16.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.rule=Host(`ntfy.outsideworx.net`)
      - traefik.http.routers.ntfy.tls.certresolver=letsencrypt
    volumes:
      - /home/outsideworx/ntfy:/etc/ntfy/data
      - ./ntfy.yaml:/etc/ntfy/server.yml
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
      POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - /home/outsideworx/data:/var/lib/postgresql/data
  postgres-exporter:
    command:
      - --web.listen-address=:81
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: postgres:5432/?sslmode=disable
      DATA_SOURCE_USER: $SPRING_DATASOURCE_USERNAME
      DATA_SOURCE_PASS: $SPRING_DATASOURCE_PASSWORD
    image: quay.io/prometheuscommunity/postgres-exporter:v0.18.1
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=365d
    container_name: prometheus
    image: prom/prometheus:v3.9.1
    restart: unless-stopped
    user: root
    volumes:
      - /home/outsideworx/prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  services:
    build: .
    container_name: services
    depends_on:
      - loki
      - postgres
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.services.entrypoints=websecure
      - traefik.http.routers.services.rule=Host(`services.outsideworx.net`)
      - traefik.http.routers.services.tls.certresolver=letsencrypt
    restart: on-failure:4
  traefik:
    container_name: traefik
    image: traefik:v3.6.12
    command:
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=info@outsideworx.net
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.traefik.address=:81
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --metrics.prometheus=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/outsideworx/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  utils:
    command: >-
      bash -c '
      cd /etc/utils &&
      pip install -r requirements.txt -q &&
      for script in *.py;
      do python "$$script" & done;
      wait'
    container_name: utils
    environment:
      DB_USERNAME: $SPRING_DATASOURCE_USERNAME
      DB_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      LOKI_PORT: 80
    image: python:3.13-slim
    restart: unless-stopped
    volumes:
      - /home/outsideworx/utils:/utils
      - ./utils:/etc/utils