x-healthcheck: &healthcheck
  interval: 5s
  retries: 2
  start_period: 1m
  timeout: 30s
services:
  authelia:
    container_name: authelia
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/api/health"]
    image: authelia/authelia:4.37
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`oauth.localhost`)
      - traefik.http.routers.authelia.tls=true
      - traefik.http.services.authelia.loadbalancer.server.port=80
    volumes:
      - ./authelia-test.yaml:/config/configuration.yml
      - ./authelia-test-users.yaml:/config/users.yaml
      - ./logo.png:/config/assets/logo.png
  grafana:
    container_name: grafana
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/api/health"]
    image: grafana/grafana:12.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=80
    volumes:
      - ./grafana-test.ini:/etc/grafana/grafana.ini
  loki:
    container_name: loki
    image: grafana/loki:3.6.4
    user: root
    volumes:
      - ./loki-test.yaml:/etc/loki/local-config.yaml
  ntfy:
    command: serve
    container_name: ntfy
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/v1/health"]
    image: binwiederhier/ntfy:v2.16.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.rule=Host(`ntfy.localhost`)
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.services.ntfy.loadbalancer.server.port=80
    volumes:
      - ./ntfy-test.yaml:/etc/ntfy/server.yml
  postgres:
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    image: postgres:16.2
    ports:
      - "5432:5432"
  postgres-exporter:
    command:
      - --web.listen-address=:80
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_PASS:
      DATA_SOURCE_URI: postgres:5432/?sslmode=disable
      DATA_SOURCE_USER: postgres
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/metrics"]
    image: quay.io/prometheuscommunity/postgres-exporter:v0.18.1
  prometheus:
    container_name: prometheus
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
    image: prom/prometheus:v3.9.1
    volumes:
      - ./prometheus-test.yaml:/etc/prometheus/prometheus.yml
  promtail:
    container_name: promtail
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "bash -c 'echo -e \"GET /ready HTTP/1.0\\r\\n\\r\\n\" > /dev/tcp/localhost/80'"]
    image: grafana/promtail:3.6.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-test.yaml:/etc/promtail/config.yml
  traefik:
    command:
      - --accesslog=true
      - --entrypoints.traefik.address=:81
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --log.noColor=true
      - --metrics.prometheus=true
      - --ping=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    container_name: traefik
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:81/ping"]
    image: traefik:v3.6.14
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  utils:
    command: >-
      bash -c '
        cd /etc/utils;
        pip install -r requirements.txt -q &&
        for script in *.py; do
          python "$$script" &
        done;
        wait'
    container_name: utils
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ""
      DB_USERNAME: postgres
    image: python:3.13-slim
    volumes:
      - cache:/utils/cache
      - ./utils:/etc/utils
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      DISABLE_VERSION_CHECK: true
      INIT_ENABLED: true
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      OAUTH_AUTO_LAUNCH: oidc
      OAUTH_OIDC_CLIENT_ID: wg-easy
      OAUTH_OIDC_CLIENT_SECRET: wg-easy
      OAUTH_OIDC_SERVER: https://oauth.localhost
      OAUTH_PROVIDERS: oidc
    extra_hosts:
      - "oauth.localhost:host-gateway"
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "node", "-e", "require('net').connect(51821,'127.0.0.1').on('connect',()=>process.exit()).on('error',()=>process.exit(1))"]
    image: ghcr.io/wg-easy/wg-easy:15
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg-easy.entrypoints=websecure
      - traefik.http.routers.wg-easy.rule=Host(`vpn.localhost`)
      - traefik.http.routers.wg-easy.tls=true
      - traefik.http.services.wg-easy.loadbalancer.server.port=51821
    ports:
      - "51820:51820/udp"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
volumes:
  cache:
