global:
  scrape_interval: 1m
scrape_configs:
  - job_name: authelia
    static_configs:
      - targets: [ "services-authelia:81" ]
  - job_name: loki
    static_configs:
      - targets: [ "services-loki" ]
  - job_name: ntfy
    static_configs:
      - targets: [ "services-ntfy:81" ]
  - job_name: postgres-exporter
    static_configs:
      - targets: [ "services-postgres-exporter" ]
  - job_name: promtail
    static_configs:
      - targets: [ "services-promtail" ]
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "services-services:81" ]
  - job_name: sites
    static_configs:
      - targets: [
        "sites-come-in-and-find-out",
        "sites-duckumbrella",
        "sites-gaiapeeps",
        "sites-igli",
        "sites-outsideworx",
        "sites-soupart",
        "sites-soupkitchen"
      ]
  - job_name: traefik
    static_configs:
      - targets: [ "services-traefik:81" ]