global:
  scrape_interval: 1m
scrape_configs:
  - job_name: loki
    static_configs:
      - targets: [ "loki" ]
  - job_name: ntfy
    static_configs:
      - targets: [ "ntfy:81" ]
  - job_name: postgres-exporter
    static_configs:
      - targets: [ "postgres-exporter:81" ]
  - job_name: sites
    static_configs:
      - targets: [
        "sites_come-in-and-find-out",
        "sites_duckumbrella",
        "sites_gaiapeeps",
        "sites_igli",
        "sites_outsideworx",
        "sites_soupart",
        "sites_soupkitchen"
      ]
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "services:81" ]
  - job_name: traefik
    static_configs:
      - targets: [ "traefik:81" ]