app:
  clients:
    ciafo:
      caller: "come-in-and-find-out"
      origin: "https://come-in-and-find-out.ch"
    peeps:
      caller: "gaiapeeps"
      origin: "https://gaiapeeps.com"
    soup:
      caller: "soupart"
      origin: "https://soupart.net"
  services:
    grafana:
      url: "https://grafana.outsideworx.net"
    loki:
      url: "http://loki"
    ntfy:
      url: "https://ntfy.outsideworx.net"
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  server:
    port: 80
server:
  port: 81
  tomcat:
    max-part-count: 50
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=76
  datasource:
    url: jdbc:postgresql://postgres:5432/
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    generate-ddl: true
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 64MB