app:
  clients:
    ciafo:
      origin: "*"
      token: "test"
    peeps:
      origin: "*"
      token: "test"
    soup:
      origin: "*"
      token: "test"
  services:
    grafana:
      url: "http://grafana.localhost"
    loki:
      url: "http://localhost:3100"
    ntfy:
      url: "http://ntfy.localhost"
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: