app:
  clients:
    ciafo:
      origin: "*"
      token: "test"
    peeps:
      origin: "*"
      token: "test"
    soup:
      origin: "*"
      token: "test"
  services:
    grafana:
      url: "https://grafana.localhost"
    loki:
      url: "http://localhost:3100"
    ntfy:
      url: "https://ntfy.localhost"
server:
  port: 8080
spring:
  cache:
    type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password:
  logout:
    url: https://oauth.localhost/logout
  security:
    oauth2:
      client:
        provider:
          authelia:
            authorization-uri: https://oauth.localhost/api/oidc/authorization
            jwk-set-uri: https://oauth.localhost/jwks.json
            token-uri: https://oauth.localhost/api/oidc/token
            user-info-uri: https://oauth.localhost/api/oidc/userinfo
        registration:
          authelia:
            client-secret: services